name: locate_your_dentist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  image_picker:
  webview_flutter:
  url_launcher:
  shared_preferences:
  connectivity_plus:
  http:
  get_storage:
  google_fonts: 4.0.4
  path_provider:
  flutter_pdfview:
  dio:
  file_picker:
  intl:
  carousel_slider:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  country_state_city_pro:
  geolocator:
  geocoding:
  razorpay_flutter:
  flutter_otp_text_field:
  country_state_city:
  pdf:
  printing: ^5.10.4
  open_filex:
  animation_list:
  flutter_staggered_animations:
  animated_custom_dropdown:
  multi_select_flutter:
  new_version_plus:
  video_compress:
  video_thumbnail:
  video_player:
  video_player_android:
  shimmer:
  fl_chart:
  flutter_quill: ^11.5.0
  flutter_quill_extensions:
  permission_handler:
  excel:
  share_plus:
  file_saver:
  crop_your_image:
  firebase_auth:
  graphview:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/indian_states.json
      - assets/fonts/Roboto-Regular.ttf
      - assets/fonts/Roboto-Bold.ttf
