// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXxg4D1aX6vQg1s19r5Pb_uO9OuIAvNNk',
    appId: '1:540179202432:web:aa86d1a145377eae3b8165',
    messagingSenderId: '540179202432',
    projectId: 'locate-your-dentist',
    authDomain: 'locate-your-dentist.firebaseapp.com',
    storageBucket: 'locate-your-dentist.firebasestorage.app',
    measurementId: 'G-DZZCQNYSGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC45Xj0VK-dYGqjdNoJVqkBJ1zlbrKvBJI',
    appId: '1:540179202432:android:b009329da500f2c73b8165',
    messagingSenderId: '540179202432',
    projectId: 'locate-your-dentist',
    storageBucket: 'locate-your-dentist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2PClpFAAxcePIVPGMP1ukEVR6d1XPlNM',
    appId: '1:540179202432:ios:b587e52f416ba1ae3b8165',
    messagingSenderId: '540179202432',
    projectId: 'locate-your-dentist',
    storageBucket: 'locate-your-dentist.firebasestorage.app',
    iosBundleId: 'com.lyd.locateYourDentist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2PClpFAAxcePIVPGMP1ukEVR6d1XPlNM',
    appId: '1:540179202432:ios:b587e52f416ba1ae3b8165',
    messagingSenderId: '540179202432',
    projectId: 'locate-your-dentist',
    storageBucket: 'locate-your-dentist.firebasestorage.app',
    iosBundleId: 'com.lyd.locateYourDentist',
  );
}
